language: node_js
sudo: true
node_js:
  - "8"
install:
  - yarn
script:
  - yarn test
  - CI=false yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build
  on:
branch: master
